# Generated by Django 6.0.4 on 2026-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='petitions/'),
        ),
    ]
